### ISSUE TITLE
PEP 561: mypy / pyright support

### ISSUE THREAD

**Issue by robbieculkin** [uktrade/to-file-like-obj#2]
Hi, thanks for providing this utility. 

Would you consider adding [PEP 561](https://peps.python.org/pep-0561/) compatibility, enabling [mypy](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages) & pyright typechecking support for importing code?

**Comment by michalc** [comment]
Probably yes!

Ah and out of curiosity really, do you have any particular use cases/projects you have in mind for to-file-like-obj?

**Comment by robbieculkin** [comment]
Glad to hear, thanks! I'm using it in conjunction with another uktrade repo, stream-zip, to stream files to s3.

**Comment by michalc** [comment]
Ah thanks for the usage info - good to know another project is useful/these are useful together.

I realise you might be wanting a timeline of when I type hints might be added. Unfortunately I can’t really promise anything - but would be open to PRs.

**Comment by nicopicchio** [comment]
Hi @robbieculkin, just a quick message to let you know that typing support has now been added to the package with its [latest release](https://github.com/uktrade/to-file-like-obj/releases/tag/v0.0.6).

**Comment by nicopicchio** [comment]
Hi @robbieculkin, just a quick message to let you know that typing support has now been added to the package with its [latest release](https://github.com/uktrade/to-file-like-obj/releases/tag/v0.0.6).
